

[0, "red", "red", "red", "red", 0, 0, "blue", 0, 0],
[0, "red", 0, 0, 0, 0, "blue", 0, "blue", 0],
[0, "red", 0, "red", "red", 0, "blue", "blue", "blue", 0],
[0, "red", 0, 0, "red", 0, "blue", 0, "blue", 0],
[0, "red", "red", "red", "red", 0, "blue", 0, "blue", 0],
[0, "green", 0, 0, "green", 0, "orange", "orange", "orange", 0],
[0, "green", "green", "green", "green", 0, "orange", 0, 0, 0],
[0, "green", "green", "green", "green", 0, "orange", "orange", "orange", 0],
[0, "green", 0, 0, "green", 0, "orange", 0, 0, 0],
[0, "green", 0, 0, "green", 0, "orange", "orange", "orange", "orange"],
[0, "yellow", "yellow", "yellow", 0, "purple", 0, 0, "purple", 0],
[0, "yellow", 0, "yellow", 0, "purple", 0, 0, "purple", 0],
[0, "yellow", 0, "yellow", 0, "purple", 0, 0, "purple", 0],
[0, "yellow", 0, "yellow", 0, 0, "purple", "purple", 0, 0],
[0, "yellow", "yellow", "yellow", 0, 0, "purple", "purple", 0, 0],
[0, "orange", "orange", "orange", 0, "cyan", "cyan", "cyan", "cyan", 0],
[0, "orange", 0, 0, 0, 0, "cyan", 0, "cyan", 0],
[0, "orange", "orange", "orange", 0, 0, "cyan", "cyan", "cyan", 0],
[0, "orange", 0, 0, 0, 0, "cyan", "cyan", 0, 0],
[0, "orange", "orange", "orange", 0, 0, "cyan", 0, "cyan", 0]